# Generated by Django 5.0.6 on 2024-06-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
