# Generated by Django 5.0.4 on 2024-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contacto',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=500),
        ),
    ]
