# Generated by Django 5.0.4 on 2024-06-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_informacioncontacto_producto_imagen_producto_precio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformacionContacto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='email',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='telefono',
        ),
    ]
